name: Tests

on:
    pull_request:
    push:
        branches:
        - master

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - resolver: lts-16
            generatemanpage: true  # only specify once, pushes to the branch
          - resolver: lts-15
          - resolver: lts-14
          - resolver: lts-12

    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.resolver }}-${{ hashFiles('stack.yaml') }}-${{ hashFiles('xmonad.cabal') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.resolver }}-${{ hashFiles('stack.yaml') }}-
            ${{ runner.os }}-${{ matrix.resolver }}-

      - name: Install dependencies
        run: |
          set -ex
          sudo apt install -y \
            libasound2-dev \
            libgmp-dev \
            libtinfo-dev \
            libx11-dev \
            libxft-dev \
            libxrandr-dev \
            libxss-dev \
            pandoc \
            #

      - name: Build and run tests
        run: |
          set -ex
          stack test --fast --no-terminal --resolver=${{ matrix.resolver }}

      - name: Generate manpage
        if: >
          github.event_name == 'push' &&
          github.event.ref == 'refs/heads/master' &&
          matrix.generatemanpage
        run: |
          set -ex
          stack exec --resolver=${{ matrix.resolver }} generatemanpage
          git config user.name github-actions
          git config user.email github-actions@github.com
          git diff --quiet --exit-code && exit
          git commit -a -m 'man: Update'
          git push
