name: Tests

on:
    pull_request:
    push:
        branches:
        - master

jobs:
  build:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        resolver: [lts-16, lts-15, lts-14, lts-12]

    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.resolver }}-${{ hashFiles('stack.yaml') }}-${{ hashFiles('xmonad.cabal') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.resolver }}-${{ hashFiles('stack.yaml') }}-
            ${{ runner.os }}-${{ matrix.resolver }}-

      - name: Install dependencies
        run: |
          set -ex
          sudo apt install -y \
            libasound2-dev \
            libgmp-dev \
            libtinfo-dev \
            libx11-dev \
            libxft-dev \
            libxrandr-dev \
            libxss-dev \
            #

      - name: Build and run tests
        run: |
          set -ex
          stack test --fast --no-terminal --resolver=${{ matrix.resolver }}
